-- Project registry migration owned by S1.
-- Session lifecycle storage is completed by the post-project compatibility
-- step in Db::run_migrations and v7.sql; do not add a competing projects
-- table or project foreign key in this migration.
